title: book_php_2017
lang: kr
description: PHP 프로그래밍 입문 도서 공부 내용 정리

theme: null

nav_version: true
edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
